import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { StyledEngineProvider } from '@mui/material/styles';
import './globals.css'

import { AuthContextProvider } from '@/context/AuthContext'
import AuthenticatedWrapper from '@/components/AuthenticatedWrapper'
import MainLayout from '@/components/MainLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledEngineProvider injectFirst>
          <AuthContextProvider>
            <AuthenticatedWrapper>
              <MainLayout>
                { children }
              </MainLayout>
            </AuthenticatedWrapper>
          </AuthContextProvider>
        </StyledEngineProvider>
      </body>
    </html>
  )
}
