# fly.toml app configuration file generated for wtr-frontend on 2023-11-19T15:18:27-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wtr-frontend"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
